name: Pulsar Manager Release

on:
  release:

jobs:
  upload:
    name: Upload Release files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build
        run: |
          version=`cat VERSION`
          ./gradlew clean distTar
          cd front-end
          npm install --save
          npm run build:prod
          mkdir -p temp-release temp-release/pulsar-manager
          cd temp-release
          cp ../distribution/LICENSE.bin.txt pulsar-manager/LICENSE
          cp ../distribution/NOTICE.bin.txt pulsar-manager/NOTICE
          cp -r ../distribution/licenses pulsar-manager/
          cp -r ../build/distributions/pulsar-manager.tar ../front-end/dist pulsar-manager
          tar -czvf apache-pulsar-manager-${version}-bin.tar.gz pulsar-manager.tar pulsar-manager

      - name: publish
        uses: skx/github-action-publish-binaries@release-0.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'apache-pulsar-manager-*'
